### ISSUE TITLE
Implement linear spin/orbit "sprint" tracking.

### ISSUE THREAD

**Issue by DavidSagan** [DavidSagan/Bmad#173]
To do:
- [ ] Create: bmad/low_level/track1_spin_sprint.f90
- [ ] Create: bmad/spin/ele_to_spin_sprint.f90
- [ ] New structure: spin_orbit_map1_struct
- [ ] Implement spin/orbit map concatenation.
- [ ] Implement PTC c_linear to spin_orbit_map1_struct
- [ ] Document sprint tracking.
