### ISSUE TITLE
update_fibre_from_ele  todo list

### ISSUE THREAD

**Issue by DavidSagan** [DavidSagan/Bmad#86]
The routine update_fibre_from_ele needs code for updating the following:

- [ ] Length, bend angle - Need to call survey
- [ ] num_steps - Need to update the linked list.
- [ ] Apertures.
- [ ] Handle zero length elements.

Note: Make sure this routine is only called when ele%bookkeeper_state%ptc = stale$.
